swagger: "2.0"
info:
  description: "Documentation for Craftbeer APIs"
  version: "1.0.0"
  title: "Craftbeer APIs"
  contact:
    email: "vu.nguyen@codeenginestudio.com"
# host: "petstore.swagger.io"
basePath: "/api/v1"
tags:
- name: "admin_account"
  description: "Operations about account used by Admin"
- name: "admin_beer"
  description: "Operations about beer used by Admin"
- name: "admin_category"
  description: "Operations about category used by Admin"
- name: "authentication"
  description: "Operations about authentication"
- name: "customer_beer"
  description: "Operations about beer used by Customer"
- name: "guest_beer"
  description: "Operations about beer used by Guest"
schemes:
- "http"
paths:
  /admin_beer:
    get:
      tags:
      - "admin_beer"
      summary: "Return all beers"
      description: "Return all beers"
      operationId: "adminGetBeer"
      produces:
      - "application/json"
      parameters:
      - name: "token"
        in: "query"
        description: "Admin token"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Beer"
        401:
          description: "Unauthorized"
  /admin_beer/{id}:
    get:
      tags:
      - "admin_beer"
      summary: "Return a beer"
      description: "Return a beer"
      operationId: "adminGetABeer"
      produces:
      - "application/json"
      parameters:
      - name: "token"
        in: "query"
        description: "Admin token"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        description: "Beer id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            $ref: "#/definitions/Beer"
        401:
          description: "Unauthorized"
        404:
          description: "Couldn't find Beer"
  /admin_beer/create:
    post:
      tags:
      - "admin_beer"
      summary: "Create new beer"
      description: "Create new beer"
      operationId: "adminCreateBeer"
      produces:
      - "application/json"
      parameters:
      - name: "token"
        in: "query"
        description: "Admin token"
        required: true
        type: "string"
      - name: "beer"
        in: "body"
        description: "Beer object"
        required: true
        schema:
          $ref: "#/definitions/BeerRequest"
      responses:
        201:
          description: "successful operation"
          schema:
            type: "object"
            $ref: "#/definitions/Beer"      
definitions:
  Beer:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      manufacturer:
        type: "string"
      name:
        type: "string"
      country:
        type: "string"
      price:
        type: "number"
        format: "float"
      description:
        type: "string"
      is_archived:
        type: "boolean"
      category:
        type: "object"
        $ref: "#/definitions/Category"
    xml:
      name: "Beer"
  BeerRequest:
    type: "object"
    properties:
      manufacturer:
        type: "string"
      name:
        type: "string"
      country:
        type: "string"
      price:
        type: "number"
        format: "float"
      description:
        type: "string"
      category_id:
        type: "integer"
        format: "int64"
    xml:
      name: "BeerRequest"
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
