swagger: "2.0"
info:
  description: "Documentation for Craftbeer APIs"
  version: "2.0.0"
  title: "Craftbeer APIs"
  contact:
    email: "vu.nguyen@codeenginestudio.com"
# host: "petstore.swagger.io"
basePath: "/api"
tags:
- name: "guest_beer"
  description: "Operations about beer used by Guest"
schemes:
- "http"
- "https"
paths:
  /guest_beer/{id}:
    get:
      tags:
      - "guest_beer"
      summary: "Get a beer"
      description: "Get a beer"
      operationId: "guestGetABeer"
      produces:
      - "application/json"
      parameters:
      - name: "Accept-Version"
        in: "header"
        description: "Specify version of API using"
        required: true
        type: "string"
      - name: "id"
        in: "path"
        description: "Beer id"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "object"
            $ref: "#/definitions/Beer"
        404:
          description: "Can not find Beer"
definitions:
  Beer:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      manufacturer:
        type: "string"
      name:
        type: "string"
      country:
        type: "string"
      price:
        type: "number"
        format: "float"
      description:
        type: "string"
      is_archived:
        type: "boolean"
      category:
        type: "object"
        $ref: "#/definitions/Category"
    xml:
      name: "Beer"
  Category:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
